title: Sigma Guide
description: Sigma's comprohensive guide.
author: Jack Timmins
logo: /sigma-guide/static/img/logo.svg
github: https://github.com/Tim-Jackins
about: To help navigate the tools of the Sigma Lab

baseurl: "https://tim-jackins.github.io/sigma-guide"
url: "https://tim-jackins.github.io/sigma-guide"

allowsearch: true

enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
