title: John Smith
description: My Personal Blog
author: John Smith
logo: /static/img/logo.svg
github: https://github.com/Tim-Jackins
about: Helping those in sigma

baseurl: "https://tim-jackins.github.io/sigma-guide/"
url: "https://tim-jackins.github.io/sigma-guide/"

allowsearch: true

enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
